apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-orderproc-api
  namespace: orderproc
spec:
  provider: azure
  secretObjects:
    - secretName: redis-secret
      type: Opaque
      data:
        - objectName: redis-connection-string
          key: REDIS_CONNECTION_STRING
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "5274679b-e0ee-44fc-aa06-ff2122977f16"
    keyvaultName: "kv-orderproc-dev01"
    tenantId: "2e8cb550-807a-4e5c-81ce-6b06740b6dfe"
    objects: |
      array:
        - |
          objectName: redis-connection-string
          objectType: secret